package pt.carolina.superpizza.wizard;

import java.awt.Graphics;
import java.awt.event.KeyAdapter;
import java.awt.event.MouseAdapter;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * This panel displays a please wait message
 * 
 */
public class WaitingGlassPanel extends JPanel {

	private static final long serialVersionUID = 1L;
	private ImageIcon waitIcon = new ImageIcon(this.getClass().getResource("wait.png"));
	private JLabel jLabel1;

	/** Creates new form WaitingGlassPanel */
	public WaitingGlassPanel() {
		initComponents();

		addMouseListener(new MouseAdapter() {
		});
		addMouseMotionListener(new MouseAdapter() {
		});
		addKeyListener(new KeyAdapter() {
		});

		waitIcon.setImageObserver(this);
	}

	@Override
	protected void paintComponent(Graphics g) {
		g.setColor(new java.awt.Color(255, 255, 255, 150));
		g.fillRect(0, 0, getWidth() - 1, getHeight() - 1);
		super.paintComponent(g);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();

		setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
		setOpaque(false);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(waitIcon);
		jLabel1.setText("PLEASE_WAIT");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
				.addContainerGap()));
	}
}
